### ISSUE TITLE
Consistency in json schema

### ISSUE THREAD

**Issue by k-florek** [cov-lineages/constellations#11]
I was hoping to use some of these constellations for a wastewater workflow I am working on and I came across slight inconsistency in the top level descriptor for a couple files. Its pretty minor but the definitions for `cAV1.json` and `cB.1.1.7.json` both use "name" while the others use "label". I can easily work around it but I was just curious if this was on purpose?

**Comment by rambaut** [comment]
Not on purpose - just a residual artefact of an older format. Thanks for pointing it out. Changed to `label`.
