### ISSUE TITLE
Constellation for B.1.1.7

### ISSUE THREAD

**Issue by hsnguyen** [cov-lineages/constellations#12]
I think coordinate for 3 synonymous sites from cB.1.1.7.json are not correct, they're 0-based instead of 1-based:

nuc:C912T
nuc:C16175T
nuc:T2680C

This resulted in scorpio call always have 3 ref alleles using this constellation file. Can you please check @rambaut ?
Thanks.

**Comment by hsnguyen** [comment]
They should be:
nuc:C913T
nuc:C16176T
nuc:T26801C

**Comment by tseemann** [comment]
@rambaut @rmcolq @aineniamh

**Comment by rambaut** [comment]
Fixed. Thanks

**Comment by hsnguyen** [comment]
@tseemann @rambaut Errors not just from coordinates, the alleles messed up to. Please check&merge the PR #14

**Comment by rambaut** [comment]
Shouldn't do this stuff early in the morning. Fixing now...
