### ISSUE TITLE
"s" (lower case) in original json "sites" field

### ISSUE THREAD

**Issue by jaquol** [cov-lineages/constellations#17]
Trying to parse the "sites" field of the json files here:

https://github.com/cov-lineages/constellations/tree/main/constellations/definitions

I found several cases where there should be a "S" (upper case) instead of "s" (lower case) for consistency across mutations (see table below).

Just reporting in case it is useful for you.

| sites | Pango_lineages | sites_converted_for_type_variants |
|---|---|---|
| s:A570D | B.1.1.7 | aa:S:A570D |
| s:D1118H | B.1.1.7 | aa:S:D1118H |
| s:D1139H | AV.1 | aa:S:D1139H |
| s:D614G | AV.1 | aa:S:D614G |
| s:D80G | AV.1 | aa:S:D80G |
| s:E484K | AV.1 | aa:S:E484K |
| s:G142D | AV.1 | aa:S:G142D |
| s:HV69- | B.1.1.7 | aa:S:HV69- |
| s:I1130V | AV.1 | aa:S:I1130V |
| s:N439K | AV.1 | aa:S:N439K |
| s:N501Y | B.1.1.7 | aa:S:N501Y |
| s:P681H | AV.1 | aa:S:P681H |
| s:P681H | B.1.1.7 | aa:S:P681H |
| s:S982A | B.1.1.7 | aa:S:S982A |
| s:T716I | B.1.1.7 | aa:S:T716I |
| s:T95I | AV.1 | aa:S:T95I |
| s:Y144- | AV.1 | aa:S:Y144- |
| s:Y144- | B.1.1.7 | aa:S:Y144-

**Comment by rmcolq** [comment]
I thought `type_variants` was case insensitive? Is that not the case?
