### ISSUE TITLE
Combining constellations with type_variant

### ISSUE THREAD

**Issue by jaquol** [cov-lineages/constellations#18]
Our team is trying to create a table of mutations (rows = samples, columns = mutations, cell value = alleles), specifically those mutations which define variants / lineages of concern (e.g. those included in the [scorpio's constellation definitions](https://github.com/cov-lineages/constellations/tree/main/constellations/definitions)).

Our plan is to use [type_variants](https://github.com/cov-lineages/type_variants).

Instead of defining and maintaining a `config.csv` for `type_variant`, we were planning to parse the json files in [scorpio's constellation definitions](https://github.com/cov-lineages/constellations/tree/main/constellations/definitions)) to extract the `sites` fields a make a list of unique mutations to be used as `config.csv`.

I guess comments / requests / issues are:

1. Do you plan to include such feature in pangolin, scorpio or type_variant?
2. nucleotide changes in scorpio's constellation definitions begin with `nuc:` while `type_variant` expects `snp:`
3. amino acid changes in scorpio's constellation definitions begin with gene name while `type_variant` expects `aa:`
4. We found some lower / upper case variability in S gene (see https://github.com/cov-lineages/constellations/issues/17)

Thanks in advance and congratulations on the great set of tools!

**Comment by rmcolq** [comment]
1. The infomation is currently accessible in a slightly different format via `scorpio haplotype` which produces a concatenated string of alleles (by default setting ref calls to - for ease of scanning).
2. Unadvertised, we can handle `snp:` variants too
3. Again we can handle `aa:` as in type_variants as we used that python script as the base file from which `scorpio` was created. I basically tried to handle anything I had seen written.
4. Case variability is handled within, but the output label is always with case as written in input JSON.

**Comment by rmcolq** [comment]
Rereading your questions:
1. I do think it would be relatively easy to do as an extension of `scorpio haplotype` with a flag. Just need to find time to do it... 
2, 3, 4. I now realise you are saying that the constellation files are not backwards compatible with `type_variants` (my response was that all `type_variants` inputs should be forwards compatible with `scorpio`

**Comment by rmcolq** [comment]
`scorpio haplotype --append-genotypes` in the latest release now creates a file per constellation, each file containing the counts and a column per variant with the allele found

**Comment by rmcolq** [comment]
Given that it is now possible for `scorpio haplotype --apend-genotypes` to act as a drop in replacement for `type_variants`, able to handle all the constellations files, I'm closing this issue. Feel free to reopen if you have further queries.
