### ISSUE TITLE
Request: co-ordinate release and version tags

### ISSUE THREAD

**Issue by fmaguire** [cov-lineages/constellations#2]
Hi,

I don't suppose the [release](https://github.com/cov-lineages/constellations/tags) and [version](https://github.com/cov-lineages/constellations/blob/main/constellations/__init__.py#L2) tags can be matched to one another?

This would help adding the constellations used to the auto-check and update of dependencies in pangolin: https://github.com/cov-lineages/pangolin/blob/master/pangolin/command.py#L327

**Comment by aineniamh** [comment]
Thanks for pointing this out! Just went to add constellations to the --update flag and noticed the same thing!
