### ISSUE TITLE
Incorrect Definition for C.37

### ISSUE THREAD

**Issue by marcoriojas** [cov-lineages/constellations#27]
I found an apparent error in the Pango definition for Lambda (C.37).  The definition includes the mutation "nuc:T1246I", which is obviously not a nucleotide mutation.  It appears to correspond to ORF1ab:T1246I (aka nsp3:T428I) and is encoded by nuc:c4002t.

**Comment by rmcolq** [comment]
Good spot. I'll update the definition now

**Comment by rmcolq** [comment]
resolved in release v0.0.16
