### ISSUE TITLE
Modifications to B.1.1.529 (Omicron) definition

### ISSUE THREAD

**Issue by rambaut** [cov-lineages/constellations#41]
Remove `nuc:C241T` - this is in the masked out region of 5' UTR and is always ambiguous in Pangolin alignments
Add `spike:Y505H` - was being called for reference in some early genomes but seems fixed in Omicron

Remove deletions, `del:6513:3` and `del:11283:9` ? Deletions are always called badly and the exact positions can be difficult to fix.

**Comment by rmcolq** [comment]
Do we want to expand the omicron or omicron (probable) while we are at it to make sure it captures those 2 outliers?
