### ISSUE TITLE
Comments in site definitions are problemaic

### ISSUE THREAD

**Issue by nekrut** [cov-lineages/constellations#45]
Lines like this (BY.2-like definition):
```
        "nuc:T22200G # spike:V231G # but this seems to be wrong aa ref allele",
```
brake all automated parsing of these json files. Perhaps a dedicated comment tag is needed. This has very bad implications for anyone who automates definition retreaval.

**Comment by rmcolq** [comment]
I deliberately added comments in such a way that the file could be parsed by the python json module. What automatic parsing are you doing?

I have reverted this change pending a major release

**Comment by nekrut** [comment]
I convert coordinates into genomic coordinates and then validate every amino acid or nucleotide change.

**Comment by rambaut** [comment]
We will be implementing this at some point soon. But we will give warning that downstream pipelines will need to be able to respect comments prefixed by `#`.
