### ISSUE TITLE
in-string comment in cBA.1.json keeps breaking backwards-compatibility with scorpio

### ISSUE THREAD

**Issue by wm75** [cov-lineages/constellations#48]
Hi, in https://github.com/cov-lineages/constellations/commit/564121a88f3af8969551abc8ec10921dc2d4dc4f you reverted comments on definition lines for now, however there is still this strangely formatted line in the new BA.1 definition:

https://github.com/cov-lineages/constellations/blob/feb3b11fcb4f7d39bfa9dd1d38852932561e6295/constellations/definitions/cBA.1.json#L25

This keeps breaking parsing of the file with scorpio 0.3.14 and I wonder what it means. Is that `#` there on purpose?

**Comment by rmcolq** [comment]
Sorry, now removed!
