### ISSUE TITLE
Compatibility definition for v0.1.11 in pangolin 

### ISSUE THREAD

**Issue by OnePotato2** [cov-lineages/constellations#67]
Following the update to v0.1.11 for constellations

https://github.com/cov-lineages/constellations/pull/66/

I installed a clean version of pangolin including the following line in the .yaml:

```
- pip
       https://github.com/cov-lineages/constellations/archive/refs/tags/v0.1.11.tar.gz
```

When verifying via pangolin --all-versions
version v0.1.10 is listed

Does https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/data_compatibility.csv
need a line entry for constellations 0.1.11?

and do you think that, when installed via yaml rather than pangolin --update, I am seeing a faulty notice for a true 0.1.11, or that the install did enforce an older version of constellations due to either my pip pointer or the pangolin logs?

**Comment by OnePotato2** [comment]
As an aside here, for that conda env, you can prompt an update from pangolin --update and it claims to update constellations, but refers to it as 0.1.10 in the subsequent --all-versions, and will attempt to update it again in a follow-up --update

**Comment by rmcolq** [comment]
No, it's a more basic issue - the git merge de-incrememented the version in the constellations init. I'll update

**Comment by rmcolq** [comment]
I think that should be solved now
